# SPDX-License-Identifier: LicenseRef-Argenox-Proprietary

BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "noxtls"
BBFILE_PATTERN_noxtls = "^${LAYERDIR}/"
BBFILE_PRIORITY_noxtls = "7"

LAYERDEPENDS_noxtls = "core"
LAYERSERIES_COMPAT_noxtls = "wrynose scarthgap"
